const express = require('express');
// 'child_process' is essential for running Linux commands on the server
const { exec } = require('child_process'); 
// 'node-fetch' is used to send the results back to the Cliq Incoming Webhook URL
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args)); 

// We are assuming the secret tokens and URLs will be set as environment variables
// on the Render platform for security.

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware to parse incoming JSON bodies (from Cliq webhooks)
app.use(express.json());

// 1. ENVIRONMENT VARIABLES 
// Token generated by Cliq when you set up the Outgoing Webhook (Step 20)
const CLIQ_SECRET_TOKEN = process.env.CLIQ_OUTGOING_TOKEN; 

// URL generated by Cliq when you create the Incoming Webhook (Step 18A)
const CLIQ_INCOMING_URL = process.env.CLIQ_INCOMING_URL; 

// 2. SAFE COMMAND WHITELIST
//    Only commands listed here can be executed by the bot.
const SAFE_COMMANDS = {
    // Command the user types: 'uptime' -> Actual shell command: 'uptime'
    'uptime': { cmd: 'uptime', desc: 'Shows how long the system has been running.' },
    
    // Command the user types: 'stats' -> Actual shell command: combined stats
    'stats': { cmd: 'df -h && free -m', desc: 'Shows disk space and memory usage.' },
    
    // Command the user types: 'whoami' -> Actual shell command: 'whoami'
    'whoami': { cmd: 'whoami', desc: 'Shows the current server user.' }
    
    // !!! DO NOT ADD COMMANDS LIKE 'rm -rf', 'reboot', or 'sudo' !!!
};

// 3. ENDPOINT TO RECEIVE COMMANDS FROM CLIQ BOT (@devatom uptime)

app.post('/cliq-command', async (req, res) => {
    // 3a. Check for environment variable configuration
    if (!CLIQ_SECRET_TOKEN || !CLIQ_INCOMING_URL) {
        console.error("Missing CLIQ environment variables.");
        // We cannot send a message back without the incoming URL, so just fail silently.
        return res.status(500).json({ status: 'error', message: 'Server configuration error.' });
    }

    // 3b. Security Check: Verify the token sent by Cliq's Outgoing Webhook
    const authHeader = req.headers['authorization'];
    if (!authHeader || authHeader !== `Zoho-Cliq ${CLIQ_SECRET_TOKEN}`) {
        console.warn('Unauthorized request attempt. Token mismatch.');
        return res.status(403).send('Forbidden: Invalid Zoho Cliq Token');
    }

    // 3c. Extract necessary data from the Cliq POST request
    const { message_details } = req.body;
    const command_text = message_details.message.text.removeAll("@devatom").trim().toLowerCase();
    const channel_id = message_details.chat.id;
    
    // Find the command in our safe whitelist
    const safe_command_data = SAFE_COMMANDS[command_text];

    if (!safe_command_data) {
        const errorMessage = `Command not found or unauthorized: **${command_text}**. Type \`@devatom help\` for options.`;
        sendCliqMessage(errorMessage, channel_id);
        // Acknowledge receipt to Cliq immediately
        return res.json({ text: `Processing command: ${command_text}` });
    }

    // 3d. Execute the command on the server
    exec(safe_command_data.cmd, (error, stdout, stderr) => {
        let output = '';
        if (error) {
            output = `[ERROR]: Command failed. ${error.message}`;
        } else if (stderr) {
            output = `[STDERR]: ${stderr}`;
        } else {
            output = stdout;
        }

        // 3e. Format the output using markdown blockquotes for Cliq
        const formattedOutput = `**DevAtom Result: ${command_text.toUpperCase()}**\n\`\`\`\n${output.trim()}\n\`\`\``;
        
        // Send the result back to Cliq using the Incoming Webhook
        sendCliqMessage(formattedOutput, channel_id);

        // Acknowledge receipt to the Cliq Outgoing Webhook immediately
        res.json({ text: `Command ${command_text} acknowledged.` });
    });
});

// 4. HELPER FUNCTION TO SEND MESSAGE BACK TO CLIQ (INCOMING WEBHOOK)
async function sendCliqMessage(text, channelId) {
    // The incoming webhook URL is expected to have the 'chat' parameter if it needs
    // to target a specific chat, but we include 'chat' in the body for flexibility.
    
    const webhookData = {
        text: text,
        bot: {
            // This is the name displayed for the message sent from the backend
            name: "DevAtom Console",
            image: "https://i.imgur.com/your-icon-link.png" // OPTIONAL
        },
        chat: channelId // Sends the message to the original channel/chat
    };

    try {
        const response = await fetch(CLIQ_INCOMING_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(webhookData),
        });
        console.log(`Message sent to Cliq. Status: ${response.status}`);
    } catch (error) {
        console.error('Error sending message to Cliq:', error);
    }
}

// 5. SERVER START

app.listen(PORT, () => {
    console.log(`DevAtom backend listening on port ${PORT}`);
});
